### ISSUE TITLE
how to add different favicon for different routers?

### ISSUE THREAD

**Issue by sunq0001** [expressjs/serve-favicon#38]
content is the same with title.

**Comment by dougwilson** [comment]
Hi @sunq0001 since web browsers only request the favicon from a single URL : `/favicon.ico` you can only have one icon per domain name. Are the different routers on different domain names?

**Comment by sunq0001** [comment]
Hi, @dougwilson  thanks for your explanation. what i mention is different routers in same domain names. i am new in Node.js and Express.  just curious to know.   as you said people won't use different favicon in same domain, then it solves my qustions. :)

**Comment by dougwilson** [comment]
Yea, this is a web browser limitation; since no matter where you are, the browser will only request the same URL. For example, if you open `http://mysite.com/foo/bar`, the browser only looks for the icon at `http://mysite.com/favicon.ico`. If you go to `http://mysite.com/admin/tools`, the browser will still only look for the icon at `http://mysite.com/favicon.ico`, so there isn't a way to have more than one anyway :)
